export const SET_FOLLOWS = "SET_FOLLOWS";
export const HYDRATE_FOLLOWS = "HYDRATE_FOLLOWS";
export const CLEAR_FOLLOWS = "CLEAR_FOLLOWS";
export const SET_PENDING_FOLLOWERS = "SET_PENDING_FOLLOWERS";

export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const SET_FOLLOWEES = "SET_FOLLOWEES";
