export const COMMENTS_APPEND_TO_END = "COMMENTS_APPEND_TO_END";
export const COMMENTS_APPEND_TO_FRONT = "COMMENTS_APPEND_TO_FRONT";
export const COMMENTS_SET_POSTID = "COMMENTS_SET_POSTID";
export const COMMENTS_SET = "COMMENTS_SET";
// export const APPEND_POSTS_TO_FRONT = "APPEND_POSTS_TO_FRONT";
// export const CLEAR_POST = "CLEAR_POST";
// export const SET_REQ = "SET_REQ";
